adds hotswap script

diff --git a/habitat-deploy/bin/hotswap b/habitat-deploy/bin/hotswap
--- a/habitat-deploy/bin/hotswap
+++ b/habitat-deploy/bin/hotswap
@@ -3,13 +3,15 @@
 set -euo pipefail
 . "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/include/._source"
 
-echo "Not implemented."
 
-exit 1
+# ### Guard Clauses
+
+# [ -f "$HABITAT_RUN_DIR/APP_SESSION_ID.txt" ] || { echo "No APP_SESSION_ID found."; exit 1; }
+
 
 # ### Includes
 
-include setContainerStatus
+include containerStatus
 include prepEnvironment
 include parseModuleInfo
 include updateOrInitModule
@@ -18,9 +20,8 @@ include startModule
 include stopModule
 include waitForModuleExit
 
-# ### Init
 
-cd "$MODULE_DEPLOY_PATH"
+# ### Init
 
 parseModuleInfo "$MODULE_LIST"
 # shellcheck disable=SC2155  # Return value is of no interest
@@ -30,37 +31,24 @@ export HABITAT_APP_SESSION_ID="$(cat "/proc/sys/kernel/random/uuid")"
 
 
 # ### Clone and/or Update modules
-setContainerStatus "update"
 
-updateOrInitAllModules "$UPDATE_MODULES" "${!MODULE_REPOS[@]}"
+updateOrInitAllModules "$MODULE_DEPLOY_PATH" "$UPDATE_MODULES" || {
+    echo "Some updates or initializations failed, see logs above."
+    exit 1
+}
 
 
 # ### Pull and build if needed and/ or enabled
-setContainerStatus "upgrade"
 
-UPGRADE_MODULES_FORCE_BUILD="yes" # TODO: Remove when detection of needing a rebuild is more robust
-upgradeAllModules "$UPGRADE_MODULES" "$UPGRADE_MODULES_FORCE_BUILD" "$UPGRADE_MODULES_SEQUENTIAL" || {
+upgradeAllModules "$MODULE_DEPLOY_PATH" "$UPGRADE_MODULES" "$UPGRADE_MODULES_FORCE_BUILD" "$UPGRADE_MODULES_SEQUENTIAL" || {
     echo "Some pull and/ or build operations failed, see logs above."
     exit 1
 }
 
-# ### Start modules
-setContainerStatus "starting"
 
-trap onTerminate SIGTERM
-startAllModules || {
+# ### Start modules
+
+startAllModules "$MODULE_DEPLOY_PATH" || {
     echo "Some start operations failed, see logs above."
     exit 1
 }
-
-# ### Wait for containers to finish or for SIGTERM
-setContainerStatus "started"
-
-waitForAllModulesExit
-
-# ### Exit
-setContainerStatus "stopped"
-
-echo "All modules have exited."
-trap - SIGTERM
-exit 0
