reconfigures modules before starting rebuilt containers

diff --git a/habitat-deploy/bin/restart b/habitat-deploy/bin/restart
--- a/habitat-deploy/bin/restart
+++ b/habitat-deploy/bin/restart
@@ -72,6 +72,10 @@ fi
 
 # ### Start modules
 
+reconfigureModules "$MODULE_DEPLOY_PATH" || {
+    echo "Some reconfiguration operations failed, see logs above."
+    exit 1
+}
 if [ -z "$ARGS_HOTSWAP" ]; then
     date +%s >"$HABITAT_RUN_DIR/.restarting"
     startModules "$MODULE_DEPLOY_PATH" "${ARGS_MODULES[@]}" || {
@@ -80,9 +84,5 @@ if [ -z "$ARGS_HOTSWAP" ]; then
     }
     rm "$HABITAT_RUN_DIR/.restarting"
 fi
-reconfigureModules "$MODULE_DEPLOY_PATH" || {
-    echo "Some reconfiguration operations failed, see logs above."
-    exit 1
-}
 
 exitImmediately
