reconfigures modules after restarting services aswell

diff --git a/habitat-deploy/bin/restart b/habitat-deploy/bin/restart
--- a/habitat-deploy/bin/restart
+++ b/habitat-deploy/bin/restart
@@ -79,11 +79,10 @@ if [ -z "$ARGS_HOTSWAP" ]; then
         exit 1
     }
     rm "$HABITAT_RUN_DIR/.restarting"
-else
-    reconfigureModules "$MODULE_DEPLOY_PATH" || {
-        echo "Some reconfiguration operations failed, see logs above."
-        exit 1
-    }
 fi
+reconfigureModules "$MODULE_DEPLOY_PATH" || {
+    echo "Some reconfiguration operations failed, see logs above."
+    exit 1
+}
 
 exitImmediately
