ensures supervisor keeps running if some modules couldn't start, so that supervisor control scripts for stopping/ restarting etc still works

diff --git a/habitat-deploy/bin/supervisor b/habitat-deploy/bin/supervisor
--- a/habitat-deploy/bin/supervisor
+++ b/habitat-deploy/bin/supervisor
@@ -76,24 +76,25 @@ upgradeModules "$MODULE_DEPLOY_PATH" "$UPGRADE_MODULES" "$UPGRADE_MODULES_FORCE_
 }
 
 
-# ### Start modules
+# ### Start modules, then wait for them to finish or SIGTERM to trigger
 setContainerStatus "starting"
 
-startModules "$MODULE_DEPLOY_PATH" || {
+if ! startModules "$MODULE_DEPLOY_PATH"; then
     echo "Some start operations failed, see logs above."
-    exit 1
-}
+    setContainerStatus "partially-started"
 
+    [ -n "$HOTSWAP_ENABLED" ] && echo "Can't start watcher, because starting some modules failed."
+    waitExitModules "$MODULE_DEPLOY_PATH" "5"
+else
+    setContainerStatus "started"
 
-# ### Wait for containers to finish or for SIGTERM
-setContainerStatus "started"
-
-if [ -n "$HOTSWAP_ENABLED" ]; then
-    startHotswapWatcher "$MODULE_DEPLOY_PATH"
-fi
-waitExitModules "$MODULE_DEPLOY_PATH" "5"
-if [ -n "$HOTSWAP_ENABLED" ]; then
-    stopHotswapWatcher
+    if [ -n "$HOTSWAP_ENABLED" ]; then
+        startHotswapWatcher "$MODULE_DEPLOY_PATH"
+    fi
+    waitExitModules "$MODULE_DEPLOY_PATH" "5"
+    if [ -n "$HOTSWAP_ENABLED" ]; then
+        stopHotswapWatcher
+    fi
 fi
 
 
