removes string delimiters around inner assoc arrays, fixes MODULE_UPDATED array not being properly filled because the function was executed in the background

diff --git a/habitat-deploy/bin/include/startModule b/habitat-deploy/bin/include/startModule
--- a/habitat-deploy/bin/include/startModule
+++ b/habitat-deploy/bin/include/startModule
@@ -53,12 +53,12 @@ startAllModules() {
     # Body
     for moduleName in "${!MODULE_DIRS[@]}"; do
         startModule "$moduleWorkdir" "$moduleName" &
-        moduleByPID["$!"]="$moduleName"
+        moduleByPID[$!]="$moduleName"
     done
     # shellcheck disable=SC2046 # Word splitting intentional
     for jobPID in $(jobs -p); do
         wait "$jobPID" || {
-            echo "Starting '${moduleByPID["$jobPID"]}' failed with exit code '$?'."
+            echo "Starting '${moduleByPID[$jobPID]}' failed with exit code '$?'."
             exitCode="1"
         }
     done
diff --git a/habitat-deploy/bin/include/stopModule b/habitat-deploy/bin/include/stopModule
--- a/habitat-deploy/bin/include/stopModule
+++ b/habitat-deploy/bin/include/stopModule
@@ -51,12 +51,12 @@ stopAllModules() {
     # Body
     for moduleName in "${!MODULE_DIRS[@]}"; do
         stopModule "$moduleWorkdir" "$moduleName" "$shutdownTimeout" &
-        moduleByPID["$!"]="$moduleName"
+        moduleByPID[$!]="$moduleName"
     done
     # shellcheck disable=SC2046 # Word splitting intentional
     for jobPID in $(jobs -p); do
         wait "$jobPID" || {
-            echo "Stopping '${moduleByPID["$jobPID"]}' failed with exit code '$?'."
+            echo "Stopping '${moduleByPID[$jobPID]}' failed with exit code '$?'."
             exitCode="1"
         }
     done
diff --git a/habitat-deploy/bin/include/updateOrInitModule b/habitat-deploy/bin/include/updateOrInitModule
--- a/habitat-deploy/bin/include/updateOrInitModule
+++ b/habitat-deploy/bin/include/updateOrInitModule
@@ -59,7 +59,6 @@ updateOrInitModule() {
     ) || exitCode="$?"
     # shellcheck disable=SC2034  # Scoped outside included function
     [ "$exitCode" -eq 0 ] && MODULE_UPDATED[$moduleName]="_"
-    [ "$exitCode" -eq 125 ] && exitCode="0"
     return "$exitCode"
 }
 
@@ -74,13 +73,19 @@ updateOrInitAllModules() {
     exitCode="0"
     # Body
     for moduleName in "${!MODULE_DIRS[@]}"; do
+        MODULE_UPDATED[$moduleName]="_"
         updateOrInitModule "$moduleWorkdir" "$moduleName" "$updateAllowed" &
-        moduleByPID["$!"]="$moduleName"
+        moduleByPID[$!]="$moduleName"
     done
     # shellcheck disable=SC2046 # Word splitting intentional
     for jobPID in $(jobs -p); do
-        wait "$jobPID" || {
-            echo "Updating or initializing '${moduleByPID["$jobPID"]}' failed with exit code '$?'."
+        moduleName="${moduleByPID[$jobPID]}"
+        wait "$jobPID"
+        exitCode="$?"
+        # shellcheck disable=SC2034  # Scoped outside included function
+        [ "$exitCode" -eq 0 ] && MODULE_UPDATED[$moduleName]="_"
+        [ "$exitCode" -eq 0 ] || [ "$exitCode" -eq 125 ] || {
+            echo "Updating or initializing '$moduleName' failed with exit code '$exitCode'."
             exitCode="1"
         }
     done
diff --git a/habitat-deploy/bin/include/upgradeModule b/habitat-deploy/bin/include/upgradeModule
--- a/habitat-deploy/bin/include/upgradeModule
+++ b/habitat-deploy/bin/include/upgradeModule
@@ -86,7 +86,7 @@ upgradeAllModules() {
     for moduleName in "${!MODULE_DIRS[@]}"; do
         upgradeModule "$moduleWorkdir" "$moduleName" "$upgradeAllowed" "$forceBuild" &
         jobPID="$!"
-        moduleByPID["$jobPID"]="$moduleName"
+        moduleByPID[$jobPID]="$moduleName"
         if [ "$sequentialMode" == "yes" ]; then
             wait "$jobPID" || {
                 echo "Upgrading '${moduleByPID["$jobPID"]}' failed with exit code '$?'."
@@ -99,7 +99,7 @@ upgradeAllModules() {
         # shellcheck disable=SC2046 # Word splitting intentional
         for jobPID in $(jobs -p); do
             wait "$jobPID" || {
-                echo "Upgrading '${moduleByPID["$jobPID"]}' failed with exit code '$?'."
+                echo "Upgrading '${moduleByPID[$jobPID]}' failed with exit code '$?'."
                 exitCode="1"
             }
         done
