further simplifies source code of module functions

diff --git a/habitat-deploy/bin/include/startModule b/habitat-deploy/bin/include/startModule
--- a/habitat-deploy/bin/include/startModule
+++ b/habitat-deploy/bin/include/startModule
@@ -11,20 +11,22 @@ echo "Loading '$(basename "${BASH_SOURCE[0]}")'..."
 
 # Include other Modules
 
-include prepEnvironment "$@"
-include parseModuleInfo "$@"
+include prepEnvironment
+include parseModuleInfo
 
 # Public Functions
 
 startModule() {
     # Args
-    local moduleName
+    local moduleWorkdir moduleName
+    moduleWorkdir="$1"; shift
     moduleName="$1"; shift
     # Vars
     local moduleDir
     moduleDir="${MODULE_DIRS[$moduleName]}"
     # Body
     (
+        cd "$moduleWorkdir"
         prepEnvironment "$moduleName"
         echo "Starting '$moduleName' ..."
         docker compose \
@@ -36,28 +38,29 @@ startModule() {
             -d \
         2> >(grep -Pv '^.*level=warning msg="(Found orphan containers.*|secret file .* does not exist)"$' >&2)
         exit "$?"
-    )
-    return "$?"
+    ) || return "$?"
+    return 0
 }
 
 startAllModules() {
+    # Args
+    local moduleWorkdir
+    moduleWorkdir="$1"; shift
     # Vars
-    local allSuccess moduleName jobPID
+    local exitCode moduleName jobPID
     declare -A moduleByPID
-    allSuccess="_"
+    exitCode="0"
     # Body
     for moduleName in "${!MODULE_DIRS[@]}"; do
-        startModule "$moduleName" &
+        startModule "$moduleWorkdir" "$moduleName" &
         moduleByPID["$!"]="$moduleName"
     done
     # shellcheck disable=SC2046 # Word splitting intentional
     for jobPID in $(jobs -p); do
-        wait "$jobPID"
-        exitCode="$?"
-        [ "$exitCode" -eq 0 ] || {
-            echo "Starting '${moduleByPID["$jobPID"]}' failed with exit code '$exitCode'."
-            allSuccess=""
+        wait "$jobPID" || {
+            echo "Starting '${moduleByPID["$jobPID"]}' failed with exit code '$?'."
+            exitCode="1"
         }
     done
-    [ -n "$allSuccess" ] || exit 1
+    return "$exitCode"
 }
diff --git a/habitat-deploy/bin/include/stopModule b/habitat-deploy/bin/include/stopModule
--- a/habitat-deploy/bin/include/stopModule
+++ b/habitat-deploy/bin/include/stopModule
@@ -11,14 +11,15 @@ echo "Loading '$(basename "${BASH_SOURCE[0]}")'..."
 
 # Include other Modules
 
-include prepEnvironment "$@"
-include parseModuleInfo "$@"
+include prepEnvironment
+include parseModuleInfo
 
 # Public Functions
 
 stopModule() {
     # Args
-    local moduleName shutdownTimeout
+    local moduleWorkdir moduleName shutdownTimeout
+    moduleWorkdir="$1"; shift
     moduleName="$1"; shift
     shutdownTimeout="$1"; shift
     # Vars
@@ -26,6 +27,7 @@ stopModule() {
     moduleDir="${MODULE_DIRS[$moduleName]}"
     # Body
     (
+        cd "$moduleWorkdir"
         prepEnvironment "$moduleName"
         echo "Stopping '$moduleName' (Timeout: ${shutdownTimeout}s)..."
         docker compose \
@@ -33,19 +35,30 @@ stopModule() {
         down \
             --timeout "$shutdownTimeout" \
         &>/dev/null
-    )
+    ) || return "$?"
+    return 0
 }
 
 stopAllModules() {
     # Args
-    local shutdownTimeout
+    local moduleWorkdir shutdownTimeout
+    moduleWorkdir="$1"; shift
     shutdownTimeout="$1"; shift
     # Vars
-    local moduleName
+    local exitCode moduleName jobPID
+    declare -A moduleByPID
+    exitCode="0"
     # Body
     for moduleName in "${!MODULE_DIRS[@]}"; do
-        stopModule "$moduleName" "$shutdownTimeout" &
+        stopModule "$moduleWorkdir" "$moduleName" "$shutdownTimeout" &
+        moduleByPID["$!"]="$moduleName"
     done
     # shellcheck disable=SC2046 # Word splitting intentional
-    wait $(jobs -p)
+    for jobPID in $(jobs -p); do
+        wait "$jobPID" || {
+            echo "Stopping '${moduleByPID["$jobPID"]}' failed with exit code '$?'."
+            exitCode="1"
+        }
+    done
+    return "$exitCode"
 }
diff --git a/habitat-deploy/bin/include/updateOrInitModule b/habitat-deploy/bin/include/updateOrInitModule
--- a/habitat-deploy/bin/include/updateOrInitModule
+++ b/habitat-deploy/bin/include/updateOrInitModule
@@ -11,7 +11,7 @@ echo "Loading '$(basename "${BASH_SOURCE[0]}")'..."
 
 # Include other Modules
 
-include parseModuleInfo "$@"
+include parseModuleInfo
 
 # Public Variables
 
@@ -21,50 +21,67 @@ declare -gA MODULE_UPDATED
 
 updateOrInitModule() {
     # Args
-    local moduleName updateAllowed
+    local moduleWorkdir moduleName updateAllowed
+    moduleWorkdir="$1"; shift
     moduleName="$1"; shift
     updateAllowed="$1"; shift
     # Vars
-    local moduleRepoUrl moduleRepoDir
+    local exitCode moduleRepoUrl moduleRepoDir
+    exitCode="0"
     moduleRepoUrl="${MODULE_REPOS[$moduleName]}"
     moduleRepoDir="${MODULE_DIRS[$moduleName]}"
     # Body
     # shellcheck disable=SC2034  # Scoped outside included function
-    MODULE_UPDATED[$moduleName]=""
-    if [ -d "$moduleRepoDir" ]; then
-        if [ "$updateAllowed" == "yes" ]; then
-            currentWorkdir="$(pwd)"
-            cd "$moduleRepoDir"
-            git fetch -p -q
-            if [ "$(git rev-list "HEAD..@{u}" --count 2>/dev/null || echo 0)" -eq "0" ]; then
-                echo "No updates for '$moduleName' available."
-            else
-                if [ -n "$(git status --porcelain)" ]; then
-                    echo "WARNING: Workdir dirty, not downloading the available update."
+    MODULE_UPDATED["$moduleName"]=""
+    (
+        cd "$moduleWorkdir"
+        if [ -d "$moduleRepoDir" ]; then
+            if [ "$updateAllowed" == "yes" ]; then
+                cd "$moduleRepoDir"
+                git fetch -p -q
+                if [ "$(git rev-list "HEAD..@{u}" --count 2>/dev/null || echo 0)" -eq "0" ]; then
+                    echo "No updates for '$moduleName' available."
+                    exit 1
                 else
-                    echo "Downloading update for '$moduleName'..."
-                    git pull && \
-                        MODULE_UPDATED["$moduleName"]="_"
+                    if [ -n "$(git status --porcelain)" ]; then
+                        echo "WARNING: Workdir dirty, not downloading the available update."
+                        exit 2
+                    else
+                        echo "Downloading update for '$moduleName'..."
+                        git pull
+                    fi
                 fi
             fi
-            cd "$currentWorkdir"; unset currentWorkdir
+        else
+            echo "Initializing module '$moduleName'..."
+            git clone "$moduleRepoUrl" "$moduleRepoDir"
         fi
-    else
-        echo "Initializing module '$moduleName'..."
-        # shellcheck disable=SC2034  # Scoped outside included function
-        git clone "$moduleRepoUrl" "$moduleRepoDir" && \
-            MODULE_UPDATED["$moduleName"]="_"
-    fi
+    ) || exitCode="$?"
+    # shellcheck disable=SC2034  # Scoped outside included function
+    [ "$exitCode" -eq 0 ] && MODULE_UPDATED["$moduleName"]="_"
+    return "$exitCode"
 }
 
 updateOrInitAllModules() {
     # Args
-    local updateAllowed
+    local moduleWorkdir updateAllowed
+    moduleWorkdir="$1"; shift
     updateAllowed="$1"; shift
     # Vars
-    local moduleName
+    local exitCode moduleName jobPID
+    declare -A moduleByPID
+    exitCode="0"
     # Body
-    for moduleName in "$@"; do
-        updateOrInitModule "$moduleName" "$updateAllowed"
+    for moduleName in "${!MODULE_DIRS[@]}"; do
+        updateOrInitModule "$moduleWorkdir" "$moduleName" "$updateAllowed" &
+        moduleByPID["$!"]="$moduleName"
     done
+    # shellcheck disable=SC2046 # Word splitting intentional
+    for jobPID in $(jobs -p); do
+        wait "$jobPID" || {
+            echo "Updating or initializing '${moduleByPID["$jobPID"]}' failed with exit code '$?'."
+            exitCode="1"
+        }
+    done
+    return "$exitCode"
 }
diff --git a/habitat-deploy/bin/include/upgradeModule b/habitat-deploy/bin/include/upgradeModule
--- a/habitat-deploy/bin/include/upgradeModule
+++ b/habitat-deploy/bin/include/upgradeModule
@@ -11,15 +11,16 @@ echo "Loading '$(basename "${BASH_SOURCE[0]}")'..."
 
 # Include other Modules
 
-include prepEnvironment "$@"
-include parseModuleInfo "$@"
-include updateOrInitModule "$@"
+include prepEnvironment
+include parseModuleInfo
+include updateOrInitModule
 
 # Public Functions
 
 upgradeModule() {
     # Args
-    local moduleName upgradeAllowed forceBuild
+    local moduleWorkdir moduleName upgradeAllowed forceBuild
+    moduleWorkdir="$1"; shift
     moduleName="$1"; shift
     upgradeAllowed="$1"; shift
     forceBuild="$1"; shift
@@ -29,6 +30,7 @@ upgradeModule() {
     moduleUpdated="${MODULE_UPDATED[$moduleName]}"
     # Body
     (
+        cd "$moduleWorkdir"
         prepEnvironment "$moduleName"
         [ "$upgradeAllowed" == "yes" ] \
             && echo "Pulling latest images for '$moduleName'..." \
@@ -65,47 +67,42 @@ upgradeModule() {
                 echo "No updates in module repository or images, running everything from local caches."
             fi
         fi
-    )
-    return "$?"
+    ) || return "$?"
+    return 0
 }
 
 upgradeAllModules() {
     # Args
-    local upgradeAllowed forceBuild sequentialMode
+    local moduleWorkdir upgradeAllowed forceBuild sequentialMode
+    moduleWorkdir="$1"; shift
     upgradeAllowed="$1"; shift
     forceBuild="$1"; shift
     sequentialMode="$1"; shift
     # Vars
-    local allSuccess moduleName jobPID
+    local exitCode moduleName jobPID
     declare -A moduleByPID
-    allSuccess="_"
-    # Nested Functions
-    waitForModuleUpgrade() {
-        # Args
-        local moduleName jobPID
-        moduleName="$1"; shift
-        jobPID="$1"; shift
-        # Body
-        wait "$jobPID"
-        exitCode="$?"
-        [ "$exitCode" -eq 0 ] || {
-            echo "Upgrading '$moduleName' failed with exit code '$exitCode'."
-        }
-        return "$exitCode"
-    }
+    exitCode="0"
     # Body
     for moduleName in "${!MODULE_DIRS[@]}"; do
-        upgradeModule "$moduleName" "$upgradeAllowed" "$forceBuild" &
+        upgradeModule "$moduleWorkdir" "$moduleName" "$upgradeAllowed" "$forceBuild" &
         jobPID="$!"
         moduleByPID["$jobPID"]="$moduleName"
         if [ "$sequentialMode" == "yes" ]; then
-            waitForModuleUpgrade "$moduleName" "$jobPID" || { allSuccess=""; break; }
+            wait "$jobPID" || {
+                echo "Upgrading '${moduleByPID["$jobPID"]}' failed with exit code '$?'."
+                exitCode="1"
+                break
+            }
         fi
     done
-    # shellcheck disable=SC2046 # Word splitting intentional
-    for jobPID in $(jobs -p); do
-        waitForModuleUpgrade "${moduleByPID["$jobPID"]}" "$jobPID" || allSuccess=""
-    done
-    unset waitForModuleUpgrade
-    [ -n "$allSuccess" ] || exit 1
+    if [ "$sequentialMode" != "yes" ]; then
+        # shellcheck disable=SC2046 # Word splitting intentional
+        for jobPID in $(jobs -p); do
+            wait "$jobPID" || {
+                echo "Upgrading '${moduleByPID["$jobPID"]}' failed with exit code '$?'."
+                exitCode="1"
+            }
+        done
+    fi
+    return "$exitCode"
 }
diff --git a/habitat-deploy/bin/supervisor b/habitat-deploy/bin/supervisor
--- a/habitat-deploy/bin/supervisor
+++ b/habitat-deploy/bin/supervisor
@@ -1,29 +1,24 @@
 #!/usr/bin/env bash
 
 set -euo pipefail
-cd "$(dirname "$(readlink -f "$0")")"
+. ./include/._source
+
+# ### Guard Clauses
+
 [ "$$" -eq 1 ] || { echo "Supervisor should only be run as PID 1."; exit 1; }
+
 
 # ### Includes
 
-declare -gA HABITAT_INCLUDE
-# shellcheck disable=SC2034  # Checked within imported scripts
-HABITAT_INCLUDE["__main__"]="_"
-include() {
-    local incName
-    incName="$1"; shift
-    # shellcheck disable=SC1090  # Intended non-constant source
-    . "./include/$incName" "$@"
-}
+include containerStatus
+include prepEnvironment
+include parseModuleInfo
+include updateOrInitModule
+include upgradeModule
+include startModule
+include stopModule
+include waitForModuleExit
 
-include containerStatus "$@"
-include prepEnvironment "$@"
-include parseModuleInfo "$@"
-include updateOrInitModule "$@"
-include upgradeModule "$@"
-include startModule "$@"
-include stopModule "$@"
-include waitForModuleExit "$@"
 
 # ### Exit function
 
@@ -32,18 +27,18 @@ onTerminate() {
     trap '' SIGTERM
     setContainerStatus "stopping"
     echo "Stop signal received, stopping all modules..."
-    stopAllModules "$(( SHUTDOWN_TIMEOUT - 10 ))"
+    stopAllModules "$MODULE_DEPLOY_PATH" "$(( SHUTDOWN_TIMEOUT - 10 ))" || :
     setContainerStatus "stopped"
     echo "All modules stopped."
     trap - SIGTERM
     exit 0
 }
 
+
 # ### Init
 setContainerStatus "init"
 
-cd "$MODULE_DEPLOY_PATH"
-
+# cd "$MODULE_DEPLOY_PATH"
 parseModuleInfo "$MODULE_LIST"
 # shellcheck disable=SC2155  # Return value is of no interest
 export HABITAT_APP_MODULES="$(printf ',%s' "${!MODULE_REPOS[@]}" | grep -Po '^,\K.*')"
@@ -54,23 +49,27 @@ export HABITAT_APP_SESSION_ID="$(cat "/proc/sys/kernel/random/uuid")"
 # ### Clone and/or Update modules
 setContainerStatus "update"
 
-updateOrInitAllModules "$UPDATE_MODULES" "${!MODULE_REPOS[@]}"
+updateOrInitAllModules "$MODULE_DEPLOY_PATH" "$UPDATE_MODULES" || {
+    echo "Some updates or initializations failed, see logs above."
+    exit 1
+}
 
 
 # ### Pull and build if needed and/ or enabled
 setContainerStatus "upgrade"
 
 UPGRADE_MODULES_FORCE_BUILD="yes" # TODO: Remove when detection of needing a rebuild is more robust
-upgradeAllModules "$UPGRADE_MODULES" "$UPGRADE_MODULES_FORCE_BUILD" "$UPGRADE_MODULES_SEQUENTIAL" || {
+upgradeAllModules "$MODULE_DEPLOY_PATH" "$UPGRADE_MODULES" "$UPGRADE_MODULES_FORCE_BUILD" "$UPGRADE_MODULES_SEQUENTIAL" || {
     echo "Some pull and/ or build operations failed, see logs above."
     exit 1
 }
+
 
 # ### Start modules
 setContainerStatus "starting"
 
 trap onTerminate SIGTERM
-startAllModules || {
+startAllModules "$MODULE_DEPLOY_PATH" || {
     echo "Some start operations failed, see logs above."
     exit 1
 }
@@ -78,7 +77,7 @@ startAllModules || {
 # ### Wait for containers to finish or for SIGTERM
 setContainerStatus "started"
 
-waitForAllModulesExit
+waitForAllModulesExit "$MODULE_DEPLOY_PATH"
 
 # ### Exit
 setContainerStatus "stopped"
