adds argument parsing include script; renames hotswap to restart and adds args for hotswapping, updating, upgrading and restricting to a set of modules; renames waitForModuleExit to waitExitModule; implements restricting functions affecting multiple modules to a set of modules; fixes module update metadata always reporting all modules as updated when updateOrInitAllModules was called; safeguards all module functions against supplying wrong module names; fixes formatting

diff --git a/habitat-deploy/bin/include/stopModule b/habitat-deploy/bin/include/stopModule
--- a/habitat-deploy/bin/include/stopModule
+++ b/habitat-deploy/bin/include/stopModule
@@ -2,16 +2,19 @@
 
 set -euo pipefail
 
+
 # Include File Header
 
 [[ -v "HABITAT_INCLUDE[__main__]" ]] || { echo "Included file potentially executed directly. Bailing."; exit 1; }
 [[ -v "HABITAT_INCLUDE[$(basename "${BASH_SOURCE[0]}" | tr '.-' '_')]" ]] && return 0
 HABITAT_INCLUDE[$(basename "${BASH_SOURCE[0]}" | tr '.-' '_')]="_"
 
+
 # Include other Modules
 
 include prepEnvironment
 include parseModuleInfo
+
 
 # Public Functions
 
@@ -23,7 +26,8 @@ stopModule() {
     shutdownTimeout="$1"; shift
     # Vars
     local moduleDir
-    moduleDir="${MODULE_DIRS[$moduleName]}"
+    moduleDir="${MODULE_DIRS[$moduleName]:-}"
+    [ -n "$moduleDir" ] || { echo "Missing metadata for module '$moduleName'."; return 1; }
     # Body
     (
         cd "$moduleWorkdir"
@@ -57,17 +61,27 @@ stopModule() {
     return 0
 }
 
-stopAllModules() {
+stopModules() {
     # Args
     local moduleWorkdir shutdownTimeout
     moduleWorkdir="$1"; shift
     shutdownTimeout="$1"; shift
+    declare -a moduleList
+    while [ "$#" -gt 0 ]; do
+        [ "$1" == "--" ] && break
+        moduleList+=("$1")
+        shift
+    done
+    if [ "${#moduleList[@]}" -eq 0 ]; then
+        moduleList=("${!MODULE_DIRS[@]}")
+    fi
     # Vars
     local exitCode moduleName jobPID
     declare -A moduleByPID
     exitCode="0"
     # Body
-    for moduleName in "${!MODULE_DIRS[@]}"; do
+    echo "Stopping modules: $(printf "%s, " "${moduleList[@]}" | sed 's/, $//')"
+    for moduleName in "${moduleList[@]}"; do
         stopModule "$moduleWorkdir" "$moduleName" "$shutdownTimeout" &
         moduleByPID[$!]="$moduleName"
     done
diff --git a/habitat-deploy/bin/include/updateOrInitModule b/habitat-deploy/bin/include/updateOrInitModule
--- a/habitat-deploy/bin/include/updateOrInitModule
+++ b/habitat-deploy/bin/include/updateOrInitModule
@@ -2,19 +2,23 @@
 
 set -euo pipefail
 
+
 # Include File Header
 
 [[ -v "HABITAT_INCLUDE[__main__]" ]] || { echo "Included file potentially executed directly. Bailing."; exit 1; }
 [[ -v "HABITAT_INCLUDE[$(basename "${BASH_SOURCE[0]}" | tr '.-' '_')]" ]] && return 0
 HABITAT_INCLUDE[$(basename "${BASH_SOURCE[0]}" | tr '.-' '_')]="_"
 
+
 # Include other Modules
 
 include parseModuleInfo
 
+
 # Public Variables
 
 declare -gA MODULE_UPDATED
+
 
 # Public Functions
 
@@ -25,18 +29,19 @@ updateOrInitModule() {
     moduleName="$1"; shift
     updateAllowed="$1"; shift
     # Vars
-    local exitCode moduleRepoUrl moduleRepoDir
+    local exitCode moduleRepo moduleDir
     exitCode="0"
-    moduleRepoUrl="${MODULE_REPOS[$moduleName]}"
-    moduleRepoDir="${MODULE_DIRS[$moduleName]}"
+    moduleRepo="${MODULE_REPOS[$moduleName]:-}"
+    moduleDir="${MODULE_DIRS[$moduleName]:-}"
+    { [ -n "$moduleRepo" ] && [ -n "$moduleDir" ]; } || { echo "Missing metadata for module '$moduleName'."; return 1; }
     # Body
     # shellcheck disable=SC2034  # Scoped outside included function
     MODULE_UPDATED[$moduleName]=""
     (
         cd "$moduleWorkdir"
-        if [ -d "$moduleRepoDir" ]; then
+        if [ -d "$moduleDir" ]; then
             if [ "$updateAllowed" == "yes" ]; then
-                cd "$moduleRepoDir"
+                cd "$moduleDir"
                 git fetch -p -q
                 if [ "$(git rev-list "HEAD..@{u}" --count 2>/dev/null || echo 0)" -eq "0" ]; then
                     echo "No updates for '$moduleName' available."
@@ -53,7 +58,7 @@ updateOrInitModule() {
             fi
         else
             echo "Initializing module '$moduleName'..."
-            git clone "$moduleRepoUrl" "$moduleRepoDir"
+            git clone "$moduleRepo" "$moduleDir"
         fi
     ) || exitCode="$?"
     # shellcheck disable=SC2034  # Scoped outside included function
@@ -61,18 +66,28 @@ updateOrInitModule() {
     return "$exitCode"
 }
 
-updateOrInitAllModules() {
+updateOrInitModules() {
     # Args
     local moduleWorkdir updateAllowed
     moduleWorkdir="$1"; shift
     updateAllowed="$1"; shift
+    declare -a moduleList
+    while [ "$#" -gt 0 ]; do
+        [ "$1" == "--" ] && break
+        moduleList+=("$1")
+        shift
+    done
+    if [ "${#moduleList[@]}" -eq 0 ]; then
+        moduleList=("${!MODULE_DIRS[@]}")
+    fi
     # Vars
     local exitCode moduleName jobPID jobReturnCode
     declare -A moduleByPID
     exitCode="0"
     # Body
-    for moduleName in "${!MODULE_DIRS[@]}"; do
-        MODULE_UPDATED[$moduleName]="_"
+    echo "Initializing/ Updating modules: $(printf "%s, " "${moduleList[@]}" | sed 's/, $//')"
+    for moduleName in "${moduleList[@]}"; do
+        MODULE_UPDATED[$moduleName]=""
         updateOrInitModule "$moduleWorkdir" "$moduleName" "$updateAllowed" &
         moduleByPID[$!]="$moduleName"
     done
diff --git a/habitat-deploy/bin/include/upgradeModule b/habitat-deploy/bin/include/upgradeModule
--- a/habitat-deploy/bin/include/upgradeModule
+++ b/habitat-deploy/bin/include/upgradeModule
@@ -2,17 +2,20 @@
 
 set -euo pipefail
 
+
 # Include File Header
 
 [[ -v "HABITAT_INCLUDE[__main__]" ]] || { echo "Included file potentially executed directly. Bailing."; exit 1; }
 [[ -v "HABITAT_INCLUDE[$(basename "${BASH_SOURCE[0]}" | tr '.-' '_')]" ]] && return 0
 HABITAT_INCLUDE[$(basename "${BASH_SOURCE[0]}" | tr '.-' '_')]="_"
 
+
 # Include other Modules
 
 include prepEnvironment
 include parseModuleInfo
 include updateOrInitModule
+
 
 # Public Functions
 
@@ -25,8 +28,9 @@ upgradeModule() {
     forceBuild="$1"; shift
     # Vars
     local moduleDir moduleUpdated imageHashesBefore imageHashesAfter
-    moduleDir="${MODULE_DIRS[$moduleName]}"
-    moduleUpdated="${MODULE_UPDATED[$moduleName]}"
+    moduleDir="${MODULE_DIRS[$moduleName]:-}"
+    moduleUpdated="${MODULE_UPDATED[$moduleName]:-}"
+    [ -n "$moduleDir" ] || { echo "Missing metadata for module '$moduleName'."; return 1; }
     # Body
     (
         cd "$moduleWorkdir"
@@ -70,19 +74,29 @@ upgradeModule() {
     return 0
 }
 
-upgradeAllModules() {
+upgradeModules() {
     # Args
     local moduleWorkdir upgradeAllowed forceBuild sequentialMode
     moduleWorkdir="$1"; shift
     upgradeAllowed="$1"; shift
     forceBuild="$1"; shift
     sequentialMode="$1"; shift
+    declare -a moduleList
+    while [ "$#" -gt 0 ]; do
+        [ "$1" == "--" ] && break
+        moduleList+=("$1")
+        shift
+    done
+    if [ "${#moduleList[@]}" -eq 0 ]; then
+        moduleList=("${!MODULE_DIRS[@]}")
+    fi
     # Vars
     local exitCode moduleName jobPID
     declare -A moduleByPID
     exitCode="0"
     # Body
-    for moduleName in "${!MODULE_DIRS[@]}"; do
+    echo "Upgrading modules: $(printf "%s, " "${moduleList[@]}" | sed 's/, $//')"
+    for moduleName in "${moduleList[@]}"; do
         upgradeModule "$moduleWorkdir" "$moduleName" "$upgradeAllowed" "$forceBuild" &
         jobPID="$!"
         moduleByPID[$jobPID]="$moduleName"
diff --git a/habitat-deploy/bin/include/waitExitModule b/habitat-deploy/bin/include/waitExitModule
--- a/habitat-deploy/bin/include/waitExitModule
+++ b/habitat-deploy/bin/include/waitExitModule
@@ -2,20 +2,23 @@
 
 set -euo pipefail
 
+
 # Include File Header
 
 [[ -v "HABITAT_INCLUDE[__main__]" ]] || { echo "Included file potentially executed directly. Bailing."; exit 1; }
 [[ -v "HABITAT_INCLUDE[$(basename "${BASH_SOURCE[0]}" | tr '.-' '_')]" ]] && return 0
 HABITAT_INCLUDE[$(basename "${BASH_SOURCE[0]}" | tr '.-' '_')]="_"
 
+
 # Include other Modules
 
 include prepEnvironment
 include parseModuleInfo
 
+
 # Public Functions
 
-waitForModuleExit() {
+waitExitModule() {
     # Args
     local moduleWorkdir moduleName restartTimeout
     moduleWorkdir="$1"; shift
@@ -24,7 +27,8 @@ waitForModuleExit() {
     # Vars
     local moduleDir
     declare -A containerIdToName
-    moduleDir="${MODULE_DIRS[$moduleName]}"
+    moduleDir="${MODULE_DIRS[$moduleName]:-}"
+    [ -n "$moduleDir" ] || { echo "Missing metadata for module '$moduleName'."; return 1; }
     # Body
     (
         cd "$moduleWorkdir"
@@ -62,7 +66,6 @@ waitForModuleExit() {
                         config --services
                     )
                 )"
-                echo "$runningServices" >"$HABITAT_RUN_DIR/runningServices.$moduleName.txt"
             done
             [ -z "$runningServices" ] && {
                 if [ -z "$exitedOnce" ]; then
@@ -95,7 +98,7 @@ waitForModuleExit() {
             exitCode="$?"
             exitedOnce="_"
             timeout="$restartTimeout"
-            if [ -f "$HABITAT_RUN_DIR/.hotswapping" ]; then
+            if [ -f "$HABITAT_RUN_DIR/.restarting" ]; then
                 timeout="300"
                 echo "Hotswap detected, waiting ${timeout}s for '$moduleName' to restart..."
             else
@@ -110,17 +113,27 @@ waitForModuleExit() {
     return 0
 }
 
-waitForAllModulesExit() {
+waitExitModules() {
     # Args
     local moduleWorkdir restartTimeout
     moduleWorkdir="$1"; shift
     restartTimeout="$1"; shift
+    declare -a moduleList
+    while [ "$#" -gt 0 ]; do
+        [ "$1" == "--" ] && break
+        moduleList+=("$1")
+        shift
+    done
+    if [ "${#moduleList[@]}" -eq 0 ]; then
+        moduleList=("${!MODULE_DIRS[@]}")
+    fi
     # Vars
     local exitCode moduleName jobPID
     declare -A moduleByPID
     exitCode="0"
     # Body
-    for moduleName in "${!MODULE_DIRS[@]}"; do
+    echo "Waiting for modules to exit: $(printf "%s, " "${moduleList[@]}" | sed 's/, $//')"
+    for moduleName in "${moduleList[@]}"; do
         waitForModuleExit "$moduleWorkdir" "$moduleName" "$restartTimeout" &
         moduleByPID[$!]="$moduleName"
     done
diff --git a/habitat-deploy/bin/restart b/habitat-deploy/bin/restart
--- a/habitat-deploy/bin/restart
+++ b/habitat-deploy/bin/restart
@@ -6,7 +6,10 @@ set -euo pipefail
 
 # ### Guard Clauses
 
-# [ -f "$HABITAT_RUN_DIR/APP_SESSION_ID.txt" ] || { echo "No APP_SESSION_ID found."; exit 1; }
+{
+    [ -f "$HABITAT_RUN_DIR/APP_SESSION_ID.txt" ] && \
+    HABITAT_APP_SESSION_ID="$(cat "$HABITAT_RUN_DIR/APP_SESSION_ID.txt")";
+} || { echo "No APP_SESSION_ID found."; exit 1; }
 
 
 # ### Includes
@@ -15,6 +18,18 @@ include parseModuleInfo
 include updateOrInitModule
 include upgradeModule
 include startModule
+include parseArgs
+
+
+# ### Args
+
+parseArgs "$@"
+ARGS_HOTSWAP="$(getFlagExists hotswap)"
+ARGS_UPDATE="$(getFlagExists update)"
+ARGS_UPGRADE="$(getFlagExists upgrade)"
+declare -a ARGS_MODULES=("${ARGS_POSITIONAL[@]}")
+
+[ -n "$ARGS_HOTSWAP" ] && ARGS_UPDATE="_"
 
 
 # ### Exit function
@@ -29,7 +44,7 @@ exitImmediately() {
 onTerminate() {
     trap '' SIGTERM
     echo "Exiting... Cleaning up..."
-    [ -f "$HABITAT_RUN_DIR/.hotswapping" ] && rm "$HABITAT_RUN_DIR/.hotswapping"
+    [ -f "$HABITAT_RUN_DIR/.restarting" ] && rm "$HABITAT_RUN_DIR/.restarting"
     echo "Stopping background tasks..."
     # shellcheck disable=SC2046 # Word splitting intentional
     kill $(jobs -p)
@@ -50,27 +65,31 @@ export HABITAT_APP_SESSION_ID="$(cat "/proc/sys/kernel/random/uuid")"
 
 # ### Clone and/or Update modules
 
-updateOrInitAllModules "$MODULE_DEPLOY_PATH" "$UPDATE_MODULES" || {
-    echo "Some updates or initializations failed, see logs above."
-    exit 1
-}
+if [ -n "$ARGS_UPDATE" ]; then
+    updateOrInitModules "$MODULE_DEPLOY_PATH" "$UPDATE_MODULES" "${ARGS_MODULES[@]}" || {
+        echo "Some updates or initializations failed, see logs above."
+        exit 1
+    }
+fi
 
 
 # ### Pull and build if needed and/ or enabled
 
-upgradeAllModules "$MODULE_DEPLOY_PATH" "$UPGRADE_MODULES" "$UPGRADE_MODULES_FORCE_BUILD" "$UPGRADE_MODULES_SEQUENTIAL" || {
-    echo "Some pull and/ or build operations failed, see logs above."
-    exit 1
-}
+if [ -n "$ARGS_UPGRADE" ]; then
+    upgradeModules "$MODULE_DEPLOY_PATH" "$UPGRADE_MODULES" "$UPGRADE_MODULES_FORCE_BUILD" "$UPGRADE_MODULES_SEQUENTIAL" "${ARGS_MODULES[@]}" || {
+        echo "Some pull and/ or build operations failed, see logs above."
+        exit 1
+    }
+fi
 
 
 # ### Start modules
 
-date +%s >"$HABITAT_RUN_DIR/.hotswapping"
-startAllModules "$MODULE_DEPLOY_PATH" || {
+date +%s >"$HABITAT_RUN_DIR/.restarting"
+startModules "$MODULE_DEPLOY_PATH" "${ARGS_MODULES[@]}" || {
     echo "Some start operations failed, see logs above."
     exit 1
 }
-rm "$HABITAT_RUN_DIR/.hotswapping"
+rm "$HABITAT_RUN_DIR/.restarting"
 
 exitImmediately
